// <auto-generated />
using System;
using DiliBeneficiary.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DiliBeneficiary.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240803163703_Initial Migration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DiliBeneficiary.Core.Entities.Beneficiary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("BeneficiaryId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<int>("CivilStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndDateInCpas")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<bool>("HasChildren")
                        .HasColumnType("boolean");

                    b.Property<string>("IbisNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Niss")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SocialWorkerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Softdelete")
                        .HasColumnType("boolean");

                    b.Property<int?>("SourceId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDateInCpas")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Beneficiaries");
                });

            modelBuilder.Entity("DiliBeneficiary.Core.Entities.Bilan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("BilanId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BeneficiaryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FormationConsultantLanguageLearningNote")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FormationConsultantNote")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FormationDifficulty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FormationFacilitiesAndStrengths")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FormationOpinion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FormationPersonalImprovments")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsFinalized")
                        .HasColumnType("boolean");

                    b.Property<string>("LanguageFormationNote")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PersonalSituationAdministrativeStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PersonalSituationFamily")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PersonalSituationFinancialSituation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PersonalSituationHealth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PersonalSituationHousing")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProfessionalExpectationFrOralLanguageScore")
                        .HasColumnType("integer");

                    b.Property<int>("ProfessionalExpectationFrWrittenLanguageScore")
                        .HasColumnType("integer");

                    b.Property<bool>("ProfessionalExpectationItKnowledgeEmail")
                        .HasColumnType("boolean");

                    b.Property<bool>("ProfessionalExpectationItKnowledgeInternet")
                        .HasColumnType("boolean");

                    b.Property<bool>("ProfessionalExpectationItKnowledgeWord")
                        .HasColumnType("boolean");

                    b.Property<string>("ProfessionalExpectationLongTerm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfessionalExpectationMediumTerm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProfessionalExpectationNlOralLanguageScore")
                        .HasColumnType("integer");

                    b.Property<int>("ProfessionalExpectationNlWrittentLanguageScore")
                        .HasColumnType("integer");

                    b.Property<string>("ProfessionalExpectationShortTermA")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfessionalExpectationShortTermB")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfessionalExpectationWorkingConditionConsultantNote")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfessionalExpectationWorkingConditionWhatIDontWant")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfessionalExpectationWorkingConditionWhatIWant")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfessionalExpectationWorkingConditionWhatMotivatesMe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfessionalExperienceKnowledge")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfessionalExperienceNote")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfessionalExperiencePointToImprove")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfessionalExperienceProblemEncountered")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfessionalExperienceWhatsRewarding")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Softdelete")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BeneficiaryId");

                    b.ToTable("Bilans");
                });

            modelBuilder.Entity("DiliBeneficiary.Core.Entities.BilanProfession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("BilanProfessionId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AcquiredBehaviouralKnowledge")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AcquiredKnowHow")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AcquiredKnowledge")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BehaviouralKnowledgeToDevelop")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("BilanId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KnowHowToDevelop")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KnowledgeToDevelop")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ProfessionId")
                        .HasColumnType("integer");

                    b.Property<bool>("Softdelete")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("BilanId");

                    b.HasIndex("ProfessionId");

                    b.ToTable("ProfessionBilans");
                });

            modelBuilder.Entity("DiliBeneficiary.Core.Entities.ContratPiis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ContratPiisId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AsTraitant")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CommentaireStatut")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateOfSigning")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdSource")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Softdelete")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("ContratPiis");
                });

            modelBuilder.Entity("DiliBeneficiary.Core.Entities.Formation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Softdelete")
                        .HasColumnType("boolean");

                    b.Property<int>("TrainingFieldId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TrainingFieldId");

                    b.ToTable("Formation");
                });

            modelBuilder.Entity("DiliBeneficiary.Core.Entities.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("LanguageId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<bool>("Softdelete")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("DiliBeneficiary.Core.Entities.MonitoringAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ActionId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Softdelete")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("MonitoringActions", (string)null);
                });

            modelBuilder.Entity("DiliBeneficiary.Core.Entities.Profession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Softdelete")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Profession");
                });

            modelBuilder.Entity("DiliBeneficiary.Core.Entities.QuarterlyMonitoring", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionComment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("BeneficiaryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MonitoringActionId")
                        .HasColumnType("integer");

                    b.Property<string>("Quarter")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReferentId")
                        .HasColumnType("integer");

                    b.Property<bool>("Softdelete")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("BeneficiaryId");

                    b.HasIndex("MonitoringActionId");

                    b.HasIndex("ReferentId");

                    b.ToTable("QuarterlyMonitorings");
                });

            modelBuilder.Entity("DiliBeneficiary.Core.Entities.Referent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.Property<bool>("Softdelete")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.ToTable("Referent");
                });

            modelBuilder.Entity("DiliBeneficiary.Core.Entities.School", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Locality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Softdelete")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("School");
                });

            modelBuilder.Entity("DiliBeneficiary.Core.Entities.SchoolRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BeneficiaryId")
                        .HasColumnType("integer");

                    b.Property<int>("CourseLevel")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("FormationId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<int>("Result")
                        .HasColumnType("integer");

                    b.Property<int>("SchoolId")
                        .HasColumnType("integer");

                    b.Property<bool>("Softdelete")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("TrainingTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BeneficiaryId");

                    b.HasIndex("FormationId");

                    b.HasIndex("SchoolId");

                    b.HasIndex("TrainingTypeId");

                    b.ToTable("SchoolRegistrations");
                });

            modelBuilder.Entity("DiliBeneficiary.Core.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Acronym")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Softdelete")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Service");
                });

            modelBuilder.Entity("DiliBeneficiary.Core.Entities.Support", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BeneficiaryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("ReasonOfClosure")
                        .HasColumnType("text");

                    b.Property<int>("ReferentId")
                        .HasColumnType("integer");

                    b.Property<bool>("Softdelete")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("BeneficiaryId");

                    b.HasIndex("ReferentId");

                    b.ToTable("Supports");
                });

            modelBuilder.Entity("DiliBeneficiary.Core.Entities.TrainingField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Softdelete")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("TrainingField");
                });

            modelBuilder.Entity("DiliBeneficiary.Core.Entities.TrainingType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Softdelete")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("TrainingType");
                });

            modelBuilder.Entity("DiliBeneficiary.Core.Entities.Beneficiary", b =>
                {
                    b.OwnsOne("DiliBeneficiary.Core.ValueObjects.Language", "ContactLanguage", b1 =>
                        {
                            b1.Property<int>("BeneficiaryId")
                                .HasColumnType("integer");

                            b1.Property<string>("SpokenLanguage")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("BeneficiaryId");

                            b1.ToTable("Beneficiaries");

                            b1.WithOwner()
                                .HasForeignKey("BeneficiaryId");
                        });

                    b.OwnsOne("DiliBeneficiary.Core.ValueObjects.Phone", "MobilePhone", b1 =>
                        {
                            b1.Property<int>("BeneficiaryId")
                                .HasColumnType("integer");

                            b1.Property<string>("PhoneNumber")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("BeneficiaryId");

                            b1.ToTable("Beneficiaries");

                            b1.WithOwner()
                                .HasForeignKey("BeneficiaryId");
                        });

                    b.OwnsOne("DiliBeneficiary.Core.ValueObjects.Language", "NativeLanguage", b1 =>
                        {
                            b1.Property<int>("BeneficiaryId")
                                .HasColumnType("integer");

                            b1.Property<string>("SpokenLanguage")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("BeneficiaryId");

                            b1.ToTable("Beneficiaries");

                            b1.WithOwner()
                                .HasForeignKey("BeneficiaryId");
                        });

                    b.OwnsOne("DiliBeneficiary.Core.ValueObjects.Phone", "Phone", b1 =>
                        {
                            b1.Property<int>("BeneficiaryId")
                                .HasColumnType("integer");

                            b1.Property<string>("PhoneNumber")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("BeneficiaryId");

                            b1.ToTable("Beneficiaries");

                            b1.WithOwner()
                                .HasForeignKey("BeneficiaryId");
                        });

                    b.OwnsOne("DiliBeneficiary.Core.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<int>("BeneficiaryId")
                                .HasColumnType("integer");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("BeneficiaryId");

                            b1.ToTable("Beneficiaries");

                            b1.WithOwner()
                                .HasForeignKey("BeneficiaryId");
                        });

                    b.OwnsOne("DiliBeneficiary.Core.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<int>("BeneficiaryId")
                                .HasColumnType("integer");

                            b1.Property<string>("EmailAddress")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("BeneficiaryId");

                            b1.ToTable("Beneficiaries");

                            b1.WithOwner()
                                .HasForeignKey("BeneficiaryId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("ContactLanguage")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("MobilePhone")
                        .IsRequired();

                    b.Navigation("NativeLanguage")
                        .IsRequired();

                    b.Navigation("Phone")
                        .IsRequired();
                });

            modelBuilder.Entity("DiliBeneficiary.Core.Entities.Bilan", b =>
                {
                    b.HasOne("DiliBeneficiary.Core.Entities.Beneficiary", "Beneficiary")
                        .WithMany("Bilans")
                        .HasForeignKey("BeneficiaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beneficiary");
                });

            modelBuilder.Entity("DiliBeneficiary.Core.Entities.BilanProfession", b =>
                {
                    b.HasOne("DiliBeneficiary.Core.Entities.Bilan", "Bilan")
                        .WithMany("BilanProfessions")
                        .HasForeignKey("BilanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiliBeneficiary.Core.Entities.Profession", "Profession")
                        .WithMany()
                        .HasForeignKey("ProfessionId");

                    b.Navigation("Bilan");

                    b.Navigation("Profession");
                });

            modelBuilder.Entity("DiliBeneficiary.Core.Entities.Formation", b =>
                {
                    b.HasOne("DiliBeneficiary.Core.Entities.TrainingField", "TrainingField")
                        .WithMany()
                        .HasForeignKey("TrainingFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingField");
                });

            modelBuilder.Entity("DiliBeneficiary.Core.Entities.QuarterlyMonitoring", b =>
                {
                    b.HasOne("DiliBeneficiary.Core.Entities.Beneficiary", "Beneficiary")
                        .WithMany("QuarterlyMonitorings")
                        .HasForeignKey("BeneficiaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiliBeneficiary.Core.Entities.MonitoringAction", "MonitoringAction")
                        .WithMany("QuarterlyMonitorings")
                        .HasForeignKey("MonitoringActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiliBeneficiary.Core.Entities.Referent", "Referent")
                        .WithMany("QuarterlyMonitorings")
                        .HasForeignKey("ReferentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beneficiary");

                    b.Navigation("MonitoringAction");

                    b.Navigation("Referent");
                });

            modelBuilder.Entity("DiliBeneficiary.Core.Entities.Referent", b =>
                {
                    b.HasOne("DiliBeneficiary.Core.Entities.Service", "Service")
                        .WithMany("Referents")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("DiliBeneficiary.Core.Entities.SchoolRegistration", b =>
                {
                    b.HasOne("DiliBeneficiary.Core.Entities.Beneficiary", "Beneficiary")
                        .WithMany("SchoolRegistrations")
                        .HasForeignKey("BeneficiaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiliBeneficiary.Core.Entities.Formation", "Formation")
                        .WithMany()
                        .HasForeignKey("FormationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiliBeneficiary.Core.Entities.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiliBeneficiary.Core.Entities.TrainingType", "TrainingType")
                        .WithMany()
                        .HasForeignKey("TrainingTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beneficiary");

                    b.Navigation("Formation");

                    b.Navigation("School");

                    b.Navigation("TrainingType");
                });

            modelBuilder.Entity("DiliBeneficiary.Core.Entities.Support", b =>
                {
                    b.HasOne("DiliBeneficiary.Core.Entities.Beneficiary", "Beneficiary")
                        .WithMany("Supports")
                        .HasForeignKey("BeneficiaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiliBeneficiary.Core.Entities.Referent", "Referent")
                        .WithMany("Supports")
                        .HasForeignKey("ReferentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beneficiary");

                    b.Navigation("Referent");
                });

            modelBuilder.Entity("DiliBeneficiary.Core.Entities.Beneficiary", b =>
                {
                    b.Navigation("Bilans");

                    b.Navigation("QuarterlyMonitorings");

                    b.Navigation("SchoolRegistrations");

                    b.Navigation("Supports");
                });

            modelBuilder.Entity("DiliBeneficiary.Core.Entities.Bilan", b =>
                {
                    b.Navigation("BilanProfessions");
                });

            modelBuilder.Entity("DiliBeneficiary.Core.Entities.MonitoringAction", b =>
                {
                    b.Navigation("QuarterlyMonitorings");
                });

            modelBuilder.Entity("DiliBeneficiary.Core.Entities.Referent", b =>
                {
                    b.Navigation("QuarterlyMonitorings");

                    b.Navigation("Supports");
                });

            modelBuilder.Entity("DiliBeneficiary.Core.Entities.Service", b =>
                {
                    b.Navigation("Referents");
                });
#pragma warning restore 612, 618
        }
    }
}
