#version: '3.4'

services:
  adminareaman.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "TenantSettings__DefaultConnectionString=Server=zekadb;Port=5432;Database=zekaAdminAreadb;User Id=postgres;Password=admin;"
      - RabbitMq__HostName=rabbitmq
    ports:
      - "9011:8080"

  clientman.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "TenantSettings__DefaultConnectionString=Server=zekadb;Port=5432;Database=zekaClientdb;User Id=postgres;Password=admin;"
      - RabbitMq__HostName=rabbitmq
    ports:
      - "9012:8080"

  zekaocelotgw:
    container_name: zekaocelotgw
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
    ports:
     - "9010:8080"

  authman.api:
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - "ConnectionStrings__Default=Server=zekadb;Port=5432;Database=zekaAuthdb;User Id=postgres;Password=admin;"
    ports:
        - "9013:8080"
