version: '3.4'

services:
  # adminareamanagement.api:
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - "ConnectionStrings__DefaultApiConnection=Server=zekaadminareadb;Port=5432;Database=zekaAdminAreadb;User Id=postgres;Password=admin;"
  #   depends_on:
  #     zekaadminareadb :
  #       condition: service_healthy
  #   ports:
  #     - "9011:8080"
   
  # zekaadminareadb:
  #   image: postgres
  #   container_name: zekaadminareadb
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=admin
  #     - POSTGRES_DB=zekaAdminAreadb
  #   restart: always
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U postgres"]
  #     interval: 1s
  #     timeout: 5s
  #     retries: 5
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/

  zekaocelotgw:
    container_name: zekaocelotgw
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
    ports:
     - "9010:8080"
