services:
  # adminareamanagement.api:
  #   image: diliwo/adminareamanagementapi
  #   container_name: zekaadminareaapi
  #   build:
  #     context: .
  #     dockerfile: Services/AdminAreaManagement/AdminAreaManagement.API/Dockerfile
  
  zekaocelotgw:
     image: diliwo/ocelotapigateway
     build:
      context: .
      dockerfile: ApiGateways/Ocelot.ApiGateway/Dockerfile
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-host
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  authmanagement.api:
    image: diliwo/authmanagementapi
    container_name: zekaauthapi
    build:
      context: ..
      dockerfile: zeka-web-api/Services/AuthManagement/AuthManagement.API/Dockerfile

# volumes:
#     postgres_data:
