using AuthManager.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql;
using Testcontainers.PostgreSql;
using Xunit;
using Zeka.PersistenceSecurity;

namespace Infrastructure.IntegrationTests;

[Trait("Issue", "46")]
[Trait("Evidence", "PlatformConformance")]
public sealed class PostgreSqlAuthRoleCatalogEvidenceTests : IAsyncLifetime
{
    private const string MigratorPassword = "test-migrator-password";
    private const string RuntimePassword = "test-runtime-password";
    private readonly PostgreSqlContainer postgres = new PostgreSqlBuilder("postgres:17-alpine").Build();

    public Task InitializeAsync() => postgres.StartAsync();
    public Task DisposeAsync() => postgres.DisposeAsync().AsTask();

    [Fact]
    public async Task Fresh_database_migrates_through_owner_assumption_and_matches_auth_manifest()
    {
        await ExecuteAdministratorAsync(ReadBootstrapScript("bootstrap-auth-roles.sql"));
        await ExecuteAdministratorAsync(ReadBootstrapScript("bootstrap-auth-roles.sql"));
        await ExecuteAdministratorAsync($"ALTER ROLE zeka_auth_migrator PASSWORD '{MigratorPassword}'; ALTER ROLE zeka_auth_runtime PASSWORD '{RuntimePassword}';");

        var migratorConnection = Connection("zeka_auth_migrator", MigratorPassword);
        await using (var migration = Context(migratorConnection))
        {
            await migration.Database.OpenConnectionAsync();
            await migration.Database.ExecuteSqlRawAsync("SET ROLE zeka_auth_owner");
            var migrations = migration.Database.GetMigrations().ToArray();
            Assert.True(migrations.Length > 1);
            await migration.GetService<IMigrator>().MigrateAsync(migrations[^2]);
            Assert.Equal([migrations[^1]], await migration.Database.GetPendingMigrationsAsync());
            await migration.GetService<IMigrator>().MigrateAsync();
            Assert.Empty(await migration.Database.GetPendingMigrationsAsync());
        }

        await using var verification = Context(migratorConnection);
        await RlsSecurityManifestVerifier.VerifyAsync(verification, typeof(AuthDbContext).Assembly);
        await new RuntimeDatabaseIdentityValidator(Connection("zeka_auth_runtime", RuntimePassword),
            "zeka_auth_runtime").StartAsync(default);

        var maskedAdministrator = new NpgsqlConnectionStringBuilder(postgres.GetConnectionString())
        {
            Options = "-c role=zeka_auth_runtime",
            Pooling = false
        }.ConnectionString;
        await Assert.ThrowsAsync<InvalidOperationException>(() =>
            new RuntimeDatabaseIdentityValidator(maskedAdministrator, "zeka_auth_runtime").StartAsync(default));

        await ExecuteAdministratorAsync($"""
            SET ROLE zeka_auth_owner;
            CREATE TABLE public.issue45_unknown_auth(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY);
            RESET ROLE;
            GRANT ALL ON TABLE public.issue45_unknown_auth TO zeka_auth_runtime;
            GRANT ALL ON SEQUENCE public.issue45_unknown_auth_id_seq TO zeka_auth_runtime;
            GRANT SELECT ON TABLE public."__EFMigrationsHistory" TO zeka_auth_runtime;
            ALTER ROLE zeka_auth_owner IN DATABASE {new NpgsqlCommandBuilder().QuoteIdentifier(new NpgsqlConnectionStringBuilder(postgres.GetConnectionString()).Database!)} SET application_name='unexpected';
            ALTER ROLE zeka_auth_migrator IN DATABASE {new NpgsqlCommandBuilder().QuoteIdentifier(new NpgsqlConnectionStringBuilder(postgres.GetConnectionString()).Database!)} SET application_name='unexpected';
            ALTER ROLE zeka_auth_runtime IN DATABASE {new NpgsqlCommandBuilder().QuoteIdentifier(new NpgsqlConnectionStringBuilder(postgres.GetConnectionString()).Database!)} SET application_name='unexpected';
            """);
        await ExecuteAdministratorAsync(ReadBootstrapScript("bootstrap-auth-roles.sql"));
        Assert.True(await ExecuteAdministratorScalarAsync<bool>("""
            SELECT
              (SELECT count(*)=0 FROM pg_catalog.pg_db_role_setting s
               JOIN pg_catalog.pg_roles r ON r.oid=s.setrole
               JOIN pg_catalog.pg_database d ON d.oid=s.setdatabase
               WHERE d.datname=pg_catalog.current_database()
                 AND r.rolname=ANY(ARRAY['zeka_auth_owner','zeka_auth_migrator','zeka_auth_runtime']))
              AND pg_catalog.has_table_privilege('zeka_auth_runtime','public."AspNetUsers"','SELECT')
              AND pg_catalog.has_table_privilege('zeka_auth_runtime','public."AspNetUsers"','INSERT')
              AND pg_catalog.has_table_privilege('zeka_auth_runtime','public."AspNetUsers"','UPDATE')
              AND pg_catalog.has_table_privilege('zeka_auth_runtime','public."AspNetUsers"','DELETE')
              AND NOT pg_catalog.has_table_privilege('zeka_auth_runtime','public."__EFMigrationsHistory"','SELECT')
              AND NOT pg_catalog.has_table_privilege('zeka_auth_runtime','public.issue45_unknown_auth','SELECT')
              AND NOT pg_catalog.has_sequence_privilege('zeka_auth_runtime','public.issue45_unknown_auth_id_seq','USAGE')
            """));
        await ExecuteAdministratorAsync("DROP TABLE public.issue45_unknown_auth");
        await RlsSecurityManifestVerifier.VerifyAsync(verification, typeof(AuthDbContext).Assembly);

        await ExecuteAdministratorAsync("""
            CREATE SCHEMA zeka;
            CREATE FUNCTION zeka.current_organisation_id() RETURNS uuid
              LANGUAGE sql SECURITY INVOKER AS 'SELECT NULL::uuid';
            CREATE FUNCTION zeka.issue46_unknown_function() RETURNS integer
              LANGUAGE sql SECURITY INVOKER AS 'SELECT 1';
            CREATE FUNCTION public.issue46_unknown_function() RETURNS integer
              LANGUAGE sql SECURITY INVOKER AS 'SELECT 1';
            CREATE TABLE public."LifecycleParticipantRegistryRevisions" ("Id" uuid PRIMARY KEY);
            CREATE TABLE public."LifecycleParticipantRegistryBindings" ("Id" uuid PRIMARY KEY);
            CREATE TABLE public."LifecycleParticipantRegistryActivation" ("Id" uuid PRIMARY KEY);
            CREATE TABLE public."OrganisationLifecycleOperations" ("Id" uuid PRIMARY KEY);
            CREATE TABLE public."OrganisationLifecycleParticipants" ("Id" uuid PRIMARY KEY);
            CREATE TABLE public.issue46_unknown_lifecycle (id uuid PRIMARY KEY);
            CREATE TABLE zeka.issue46_unknown_lifecycle (id uuid PRIMARY KEY);
            GRANT CREATE, USAGE ON SCHEMA zeka TO zeka_auth_runtime;
            GRANT ALL ON ALL TABLES IN SCHEMA public, zeka TO zeka_auth_runtime;
            GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public, zeka TO zeka_auth_runtime;
            """);

        await ExecuteAdministratorAsync(ReadBootstrapScript("bootstrap-auth-roles.sql"));
        await ExecuteAdministratorAsync(ReadBootstrapScript("bootstrap-auth-roles.sql"));

        Assert.True(await ExecuteAdministratorScalarAsync<bool>(ExactLifecycleTablePrivilegesSql));
        Assert.True(await ExecuteAdministratorScalarAsync<bool>("""
            SELECT
              pg_catalog.has_schema_privilege('zeka_auth_runtime', 'public', 'USAGE')
              AND NOT pg_catalog.has_schema_privilege('zeka_auth_runtime', 'public', 'CREATE')
              AND pg_catalog.has_schema_privilege('zeka_auth_runtime', 'zeka', 'USAGE')
              AND NOT pg_catalog.has_schema_privilege('zeka_auth_runtime', 'zeka', 'CREATE')
              AND (
                SELECT pg_catalog.array_agg(n.nspname || '.' || p.proname ORDER BY n.nspname, p.proname)
                FROM pg_catalog.pg_proc p
                JOIN pg_catalog.pg_namespace n ON n.oid=p.pronamespace
                WHERE n.nspname=ANY(ARRAY['public','zeka'])
                  AND pg_catalog.has_function_privilege('zeka_auth_runtime', p.oid, 'EXECUTE')
              ) = ARRAY['zeka.current_organisation_id']
            """));

        await ExecuteAdministratorAsync("""
            DROP TABLE public."LifecycleParticipantRegistryRevisions",
              public."LifecycleParticipantRegistryBindings",
              public."LifecycleParticipantRegistryActivation",
              public."OrganisationLifecycleOperations",
              public."OrganisationLifecycleParticipants",
              public.issue46_unknown_lifecycle,
              zeka.issue46_unknown_lifecycle;
            DROP FUNCTION public.issue46_unknown_function();
            DROP SCHEMA zeka CASCADE;
            """);
        await ExecuteAdministratorAsync(ReadBootstrapScript("bootstrap-auth-roles.sql"));
        await RlsSecurityManifestVerifier.VerifyAsync(verification, typeof(AuthDbContext).Assembly);
    }

    private static AuthDbContext Context(string connectionString) => new(
        new DbContextOptionsBuilder<AuthDbContext>().UseNpgsql(connectionString).Options);

    private string Connection(string username, string password) =>
        new NpgsqlConnectionStringBuilder(postgres.GetConnectionString())
        { Username = username, Password = password }.ConnectionString;

    private async Task ExecuteAdministratorAsync(string sql)
    {
        await using var connection = new NpgsqlConnection(postgres.GetConnectionString());
        await connection.OpenAsync();
        await using var command = new NpgsqlCommand(sql, connection);
        await command.ExecuteNonQueryAsync();
    }

    private async Task<T> ExecuteAdministratorScalarAsync<T>(string sql)
    {
        await using var connection = new NpgsqlConnection(postgres.GetConnectionString());
        await connection.OpenAsync();
        await using var command = new NpgsqlCommand(sql, connection);
        return (T)(await command.ExecuteScalarAsync())!;
    }

    private static string ReadBootstrapScript(string fileName)
    {
        var directory = new DirectoryInfo(AppContext.BaseDirectory);
        while (directory is not null)
        {
            var candidate = Path.Combine(directory.FullName, "Deployments", "database", fileName);
            if (File.Exists(candidate)) return File.ReadAllText(candidate);
            directory = directory.Parent;
        }
        throw new FileNotFoundException("The reviewed database role bootstrap script was not found.", fileName);
    }

    private const string ExactLifecycleTablePrivilegesSql = """
        WITH privilege_names(privilege) AS (
          VALUES ('SELECT'),('INSERT'),('UPDATE'),('DELETE'),('TRUNCATE'),('REFERENCES'),('TRIGGER')
        ), expected(table_name, privilege) AS (
          SELECT table_name, privilege
          FROM unnest(ARRAY[
            'AspNetRoleClaims','AspNetRoles','AspNetUserClaims','AspNetUserLogins','AspNetUserRoles',
            'AspNetUserTokens','AspNetUsers','AuditEntries','IdempotencyRecords','OrganisationMemberships',
            'Organisations','OutboxMessages','PermissionSets'
          ]) table_name
          CROSS JOIN unnest(ARRAY['SELECT','INSERT','UPDATE','DELETE']) privilege
          UNION ALL VALUES
            ('LifecycleParticipantRegistryRevisions','SELECT'),
            ('LifecycleParticipantRegistryBindings','SELECT'),
            ('LifecycleParticipantRegistryActivation','SELECT'),
            ('OrganisationLifecycleOperations','SELECT'),
            ('OrganisationLifecycleOperations','INSERT'),
            ('OrganisationLifecycleOperations','UPDATE'),
            ('OrganisationLifecycleParticipants','SELECT'),
            ('OrganisationLifecycleParticipants','INSERT')
        ), actual(table_name, privilege) AS (
          SELECT c.relname, privilege_names.privilege
          FROM pg_catalog.pg_class c
          JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace
          CROSS JOIN privilege_names
          WHERE n.nspname=ANY(ARRAY['public','zeka'])
            AND c.relkind IN ('r','p')
            AND pg_catalog.has_table_privilege(
              'zeka_auth_runtime',
              pg_catalog.format('%I.%I', n.nspname, c.relname),
              privilege_names.privilege)
        )
        SELECT NOT EXISTS (SELECT * FROM actual EXCEPT SELECT * FROM expected)
          AND NOT EXISTS (SELECT * FROM expected EXCEPT SELECT * FROM actual)
        """;
}
