apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminareaapi-deployment
  labels:
    app: adminareaapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminareaapi
  template:
    metadata:
      name: adminareaapi-pod
      labels:
        app: adminareaapi
    spec:
      containers:
        - name: adminareaapi
          image: diliwo/adminareamanapi:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: TenantSettings__DefaultConnectionString
              valueFrom:
                  configMapKeyRef:
                    name: adminarea-configmap
                    key: connection_string
            - name: RabbitMq__HostName
              valueFrom:
                  configMapKeyRef:
                    name: adminarea-configmap
                    key: rabbitmq_host
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      initContainers:
        - name: wait-for-db
          image: busybox
          command: ['sh', '-c', 'until nc -z zekadb-service 5432; do echo waiting for database; sleep 2; done;']
---
apiVersion: v1
kind: Service
metadata:
  name: adminareaapi-external-service
spec:
  type: LoadBalancer
  selector:
    app: adminareaapi
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: adminareaapi-service
spec:
  type: ClusterIP
  selector:
    app: adminareaapi
  ports:
  - port: 8080
    targetPort: 8080