// <auto-generated />
using System;
using AdminAreaManagement.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AdminAreaManagement.Infrastructure.Migrations
{
    [DbContext(typeof(DeploymentDbContext))]
    [Migration("20260910165920_ExplicitTenantEnforcement")]
    partial class ExplicitTenantEnforcement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AdminAreaManagement.Core.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("CityId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NormalizedCountry")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasComputedColumnSql("public.zeka_city_key(\"Country\")", true)
                        .UseCollation("C");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasComputedColumnSql("public.zeka_city_key(\"Name\")", true)
                        .UseCollation("C");

                    b.Property<bool>("Softdelete")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName", "NormalizedCountry")
                        .IsUnique()
                        .HasDatabaseName("UX_Cities_ActiveNormalizedIdentity")
                        .HasFilter("NOT \"Softdelete\"");

                    b.ToTable("Cities", null, t =>
                        {
                            t.HasCheckConstraint("CK_Cities_Country_Text", "\"Country\" COLLATE \"C\" = public.zeka_city_text(\"Country\") COLLATE \"C\" AND char_length(\"Country\") BETWEEN 1 AND 100");

                            t.HasCheckConstraint("CK_Cities_Name_Text", "\"Name\" COLLATE \"C\" = public.zeka_city_text(\"Name\") COLLATE \"C\" AND char_length(\"Name\") BETWEEN 1 AND 100");
                        });
                });

            modelBuilder.Entity("AdminAreaManagement.Core.Entities.DocumentPartner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid");

                    b.Property<int>("PartnerId")
                        .HasColumnType("integer");

                    b.Property<bool>("Softdelete")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "OrganisationId");

                    b.HasIndex("PartnerId", "OrganisationId");

                    b.ToTable("DocumentPartners");
                });

            modelBuilder.Entity("AdminAreaManagement.Core.Entities.Nationality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("NationalityId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Softdelete")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Nationalities");
                });

            modelBuilder.Entity("AdminAreaManagement.Core.Entities.Partner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressCity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Address_City");

                    b.Property<string>("AddressNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Address_Number");

                    b.Property<string>("AddressPostalCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Address_PostalCode");

                    b.Property<string>("AddressStreet")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Address_Street");

                    b.Property<int>("CategoryOfPartner")
                        .HasColumnType("integer");

                    b.Property<string>("CategoryOfPartnerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateOfAgreementSignature")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DateOfConclusion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool?>("IsEconomieSociale")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid");

                    b.Property<int>("PartnerNumber")
                        .HasColumnType("integer");

                    b.Property<bool>("Softdelete")
                        .HasColumnType("boolean");

                    b.Property<int>("StaffMemberId")
                        .HasColumnType("integer");

                    b.Property<int>("StatusOfPartner")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId", "PartnerNumber")
                        .IsUnique();

                    b.HasIndex("StaffMemberId", "OrganisationId");

                    b.ToTable("Partners");
                });

            modelBuilder.Entity("AdminAreaManagement.Core.Entities.Profession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Softdelete")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Professions");
                });

            modelBuilder.Entity("AdminAreaManagement.Core.Entities.School", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Locality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Softdelete")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Schools");
                });

            modelBuilder.Entity("AdminAreaManagement.Core.Entities.StaffMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganisationMembershipId")
                        .HasColumnType("uuid");

                    b.Property<long>("ProjectionVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<bool>("Softdelete")
                        .HasColumnType("boolean");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId", "OrganisationMembershipId")
                        .IsUnique();

                    b.HasIndex("OrganisationId", "UserName")
                        .IsUnique();

                    b.HasIndex("TeamId", "OrganisationId");

                    b.ToTable("StaffMembers", t =>
                        {
                            t.HasCheckConstraint("CK_StaffMembers_Membership", "\"OrganisationMembershipId\" <> '00000000-0000-0000-0000-000000000000'");
                        });
                });

            modelBuilder.Entity("AdminAreaManagement.Core.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Acronym")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Softdelete")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId", "Acronym")
                        .IsUnique();

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("AdminAreaManagement.Core.Entities.Training", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Softdelete")
                        .HasColumnType("boolean");

                    b.Property<int>("TrainingFieldId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TrainingFieldId");

                    b.ToTable("Trainings");
                });

            modelBuilder.Entity("AdminAreaManagement.Core.Entities.TrainingField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("TrainingFieldId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Softdelete")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("TrainingFields");
                });

            modelBuilder.Entity("AdminAreaManagement.Core.Entities.TrainingType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("TrainingTypeId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Softdelete")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("TrainingTypes");
                });

            modelBuilder.Entity("AdminAreaManagement.Core.ValueObjects.ContactPerson", b =>
                {
                    b.Property<int>("PartnerId")
                        .HasColumnType("integer");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContactDetails")
                        .HasColumnType("text");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<bool>("ToDelete")
                        .HasColumnType("boolean");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PartnerId", "OrganisationId", "ContactDetails", "Gender", "ToDelete");

                    b.ToTable("ContactPersons", (string)null);
                });

            modelBuilder.Entity("AdminAreaManagement.Core.ValueObjects.Email", b =>
                {
                    b.Property<int>("PartnerId")
                        .HasColumnType("integer");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PartnerId", "OrganisationId", "Id");

                    b.ToTable("Emails", (string)null);
                });

            modelBuilder.Entity("AdminAreaManagement.Infrastructure.Messaging.StaffProjectionMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Softdelete")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "OrganisationId");

                    b.HasIndex("OrganisationId", "EventId")
                        .IsUnique();

                    b.ToTable("StaffProjectionOutbox", (string)null);
                });

            modelBuilder.Entity("AdminAreaManagement.Core.Entities.DocumentPartner", b =>
                {
                    b.HasOne("AdminAreaManagement.Core.Entities.Partner", "Partner")
                        .WithMany("Documents")
                        .HasForeignKey("PartnerId", "OrganisationId")
                        .HasPrincipalKey("Id", "OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("AdminAreaManagement.Core.Entities.Partner", b =>
                {
                    b.HasOne("AdminAreaManagement.Core.Entities.StaffMember", "StaffMember")
                        .WithMany()
                        .HasForeignKey("StaffMemberId", "OrganisationId")
                        .HasPrincipalKey("Id", "OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StaffMember");
                });

            modelBuilder.Entity("AdminAreaManagement.Core.Entities.StaffMember", b =>
                {
                    b.HasOne("AdminAreaManagement.Core.Entities.Team", "Team")
                        .WithMany("StaffMembers")
                        .HasForeignKey("TeamId", "OrganisationId")
                        .HasPrincipalKey("Id", "OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("AdminAreaManagement.Core.Entities.Training", b =>
                {
                    b.HasOne("AdminAreaManagement.Core.Entities.TrainingField", "TrainingField")
                        .WithMany()
                        .HasForeignKey("TrainingFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingField");
                });

            modelBuilder.Entity("AdminAreaManagement.Core.ValueObjects.ContactPerson", b =>
                {
                    b.HasOne("AdminAreaManagement.Core.Entities.Partner", null)
                        .WithMany("ContactPersons")
                        .HasForeignKey("PartnerId", "OrganisationId")
                        .HasPrincipalKey("Id", "OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AdminAreaManagement.Core.ValueObjects.Email", b =>
                {
                    b.HasOne("AdminAreaManagement.Core.Entities.Partner", null)
                        .WithMany("Emails")
                        .HasForeignKey("PartnerId", "OrganisationId")
                        .HasPrincipalKey("Id", "OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AdminAreaManagement.Core.Entities.Partner", b =>
                {
                    b.Navigation("ContactPersons");

                    b.Navigation("Documents");

                    b.Navigation("Emails");
                });

            modelBuilder.Entity("AdminAreaManagement.Core.Entities.Team", b =>
                {
                    b.Navigation("StaffMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
