using ClientManagement.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql;
using Testcontainers.PostgreSql;
using Xunit;
using Zeka.PersistenceSecurity;

namespace Infrastructure.IntegrationTests;

[Trait("Issue", "46")]
[Trait("Evidence", "PlatformConformance")]
public sealed class PostgreSqlClientRoleCatalogEvidenceTests : IAsyncLifetime
{
    private const string MigratorPassword = "test-migrator-password";
    private const string RuntimePassword = "test-runtime-password";
    private readonly PostgreSqlContainer postgres = new PostgreSqlBuilder("postgres:17-alpine").Build();

    public Task InitializeAsync() => postgres.StartAsync();
    public Task DisposeAsync() => postgres.DisposeAsync().AsTask();

    [Fact]
    public async Task Fresh_database_migrates_through_owner_assumption_and_matches_client_manifest()
    {
        await ExecuteAdministratorAsync(ReadBootstrapScript("bootstrap-client-roles.sql"));
        await ExecuteAdministratorAsync(ReadBootstrapScript("bootstrap-client-roles.sql"));
        await ExecuteAdministratorAsync($"ALTER ROLE zeka_client_migrator PASSWORD '{MigratorPassword}'; ALTER ROLE zeka_client_runtime PASSWORD '{RuntimePassword}';");

        var migratorConnection = Connection("zeka_client_migrator", MigratorPassword);
        await using (var deployment = Deployment(migratorConnection))
        {
            await deployment.Database.OpenConnectionAsync();
            await deployment.Database.ExecuteSqlRawAsync("SET ROLE zeka_client_owner");
            await deployment.Database.ExecuteSqlInterpolatedAsync($"""
                CREATE TABLE "__OrganisationTenantMap"
                  ("TenantName" text PRIMARY KEY, "OrganisationId" uuid NOT NULL UNIQUE)
                """);
            var migrations = deployment.Database.GetMigrations().ToArray();
            Assert.True(migrations.Length > 1);
            await deployment.GetService<IMigrator>().MigrateAsync(migrations[^2]);
            Assert.Equal([migrations[^1]], await deployment.Database.GetPendingMigrationsAsync());
            await deployment.GetService<IMigrator>().MigrateAsync();
            Assert.Empty(await deployment.Database.GetPendingMigrationsAsync());
        }

        await using var verification = Deployment(migratorConnection);
        await RlsSecurityManifestVerifier.VerifyAsync(verification, typeof(ApplicationDbContext).Assembly);
        await new RuntimeDatabaseIdentityValidator(Connection("zeka_client_runtime", RuntimePassword),
            "zeka_client_runtime").StartAsync(default);

        var maskedAdministrator = new NpgsqlConnectionStringBuilder(postgres.GetConnectionString())
        {
            Options = "-c role=zeka_client_runtime",
            Pooling = false
        }.ConnectionString;
        await Assert.ThrowsAsync<InvalidOperationException>(() =>
            new RuntimeDatabaseIdentityValidator(maskedAdministrator, "zeka_client_runtime").StartAsync(default));

        var databaseIdentifier = new NpgsqlCommandBuilder().QuoteIdentifier(
            new NpgsqlConnectionStringBuilder(postgres.GetConnectionString()).Database!);
        await ExecuteAdministratorAsync($"""
            SET ROLE zeka_client_owner;
            CREATE TABLE public.issue45_unknown_client(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY);
            RESET ROLE;
            GRANT ALL ON TABLE public.issue45_unknown_client TO zeka_client_runtime;
            GRANT ALL ON SEQUENCE public.issue45_unknown_client_id_seq TO zeka_client_runtime;
            GRANT INSERT, UPDATE, DELETE ON TABLE public."Languages" TO zeka_client_runtime;
            GRANT USAGE, SELECT ON SEQUENCE public."Languages_LanguageId_seq" TO zeka_client_runtime;
            GRANT SELECT ON TABLE public."__EFMigrationsHistory" TO zeka_client_runtime;
            GRANT ALL ON TABLE public."OrganisationExportFences" TO zeka_client_runtime;
            GRANT ALL ON TABLE public."OrganisationExportFragments" TO zeka_client_runtime;
            GRANT ALL ON TABLE public."OrganisationExportInbox" TO zeka_client_runtime;
            GRANT ALL ON TABLE public."OrganisationExportOutbox" TO zeka_client_runtime;
            GRANT UPDATE ("FenceToken") ON TABLE public."OrganisationExportFences" TO PUBLIC;
            GRANT EXECUTE ON FUNCTION zeka.reject_writes_during_export_fence() TO PUBLIC;
            ALTER ROLE zeka_client_owner IN DATABASE {databaseIdentifier} SET application_name='unexpected';
            ALTER ROLE zeka_client_migrator IN DATABASE {databaseIdentifier} SET application_name='unexpected';
            ALTER ROLE zeka_client_runtime IN DATABASE {databaseIdentifier} SET application_name='unexpected';
            """);
        await ExecuteAdministratorAsync(ReadBootstrapScript("bootstrap-client-roles.sql"));
        Assert.True(await ExecuteAdministratorScalarAsync<bool>("""
            SELECT
              (SELECT count(*)=0 FROM pg_catalog.pg_db_role_setting s
               JOIN pg_catalog.pg_roles r ON r.oid=s.setrole
               JOIN pg_catalog.pg_database d ON d.oid=s.setdatabase
               WHERE d.datname=pg_catalog.current_database()
                 AND r.rolname=ANY(ARRAY['zeka_client_owner','zeka_client_migrator','zeka_client_runtime']))
              AND pg_catalog.has_table_privilege('zeka_client_runtime','public."Languages"','SELECT')
              AND NOT pg_catalog.has_table_privilege('zeka_client_runtime','public."Languages"','INSERT')
              AND NOT pg_catalog.has_table_privilege('zeka_client_runtime','public."Languages"','UPDATE')
              AND NOT pg_catalog.has_table_privilege('zeka_client_runtime','public."Languages"','DELETE')
              AND NOT pg_catalog.has_sequence_privilege('zeka_client_runtime','public."Languages_LanguageId_seq"','USAGE')
              AND NOT pg_catalog.has_sequence_privilege('zeka_client_runtime','public."Languages_LanguageId_seq"','SELECT')
              AND NOT pg_catalog.has_table_privilege('zeka_client_runtime','public."__EFMigrationsHistory"','SELECT')
              AND NOT pg_catalog.has_table_privilege('zeka_client_runtime','public.issue45_unknown_client','SELECT')
              AND NOT pg_catalog.has_sequence_privilege('zeka_client_runtime','public.issue45_unknown_client_id_seq','USAGE')
              AND (
                SELECT pg_catalog.bool_and(pg_catalog.has_table_privilege(
                  'zeka_client_runtime', pg_catalog.format('public.%I', object_name), privilege_name))
                FROM (VALUES
                  ('OrganisationExportFences'), ('OrganisationExportFragments'),
                  ('OrganisationExportInbox'), ('OrganisationExportOutbox')) AS objects(object_name)
                CROSS JOIN (VALUES ('SELECT'), ('INSERT')) AS privileges(privilege_name)
              )
              AND (
                SELECT pg_catalog.bool_and(NOT pg_catalog.has_table_privilege(
                  'zeka_client_runtime', pg_catalog.format('public.%I', object_name), privilege_name))
                FROM (VALUES
                  ('OrganisationExportFences'), ('OrganisationExportFragments'),
                  ('OrganisationExportInbox'), ('OrganisationExportOutbox')) AS objects(object_name)
                CROSS JOIN (VALUES
                  ('UPDATE'), ('DELETE'), ('TRUNCATE'), ('REFERENCES'), ('TRIGGER')) AS privileges(privilege_name)
              )
              AND pg_catalog.has_column_privilege(
                'zeka_client_runtime', 'public."OrganisationExportFences"', 'ReleasedAt', 'UPDATE')
              AND NOT EXISTS (
                SELECT 1
                FROM (VALUES
                  ('OrganisationExportFences'), ('OrganisationExportFragments'),
                  ('OrganisationExportInbox'), ('OrganisationExportOutbox')) AS objects(object_name)
                JOIN pg_catalog.pg_class relation
                  ON relation.oid=pg_catalog.to_regclass(pg_catalog.format('public.%I', object_name))
                JOIN pg_catalog.pg_attribute attribute ON attribute.attrelid=relation.oid
                CROSS JOIN LATERAL pg_catalog.aclexplode(attribute.attacl) acl
                WHERE attribute.attnum>0 AND NOT attribute.attisdropped
                  AND acl.grantee<>relation.relowner
                  AND NOT (
                    object_name='OrganisationExportFences'
                    AND attribute.attname='ReleasedAt'
                    AND acl.grantee=(SELECT oid FROM pg_catalog.pg_roles WHERE rolname='zeka_client_runtime')
                    AND acl.privilege_type='UPDATE')
              )
              AND (
                SELECT pg_catalog.bool_and(pg_catalog.has_sequence_privilege(
                  'zeka_client_runtime', pg_catalog.format('public.%I', object_name), privilege_name))
                FROM (VALUES
                  ('OrganisationExportFences_Id_seq'), ('OrganisationExportFragments_Id_seq'),
                  ('OrganisationExportInbox_Id_seq'), ('OrganisationExportOutbox_Id_seq')) AS objects(object_name)
                CROSS JOIN (VALUES ('USAGE'), ('SELECT')) AS privileges(privilege_name)
              )
              AND (
                SELECT pg_catalog.bool_and(NOT pg_catalog.has_sequence_privilege(
                  'zeka_client_runtime', pg_catalog.format('public.%I', object_name), 'UPDATE'))
                FROM (VALUES
                  ('OrganisationExportFences_Id_seq'), ('OrganisationExportFragments_Id_seq'),
                  ('OrganisationExportInbox_Id_seq'), ('OrganisationExportOutbox_Id_seq')) AS objects(object_name)
              )
              AND pg_catalog.has_function_privilege(
                'zeka_client_runtime', 'zeka.reject_writes_during_export_fence()', 'EXECUTE')
              AND NOT EXISTS (
                SELECT 1
                FROM pg_catalog.pg_proc procedure
                CROSS JOIN LATERAL pg_catalog.aclexplode(
                  COALESCE(procedure.proacl, pg_catalog.acldefault('f', procedure.proowner))) acl
                WHERE procedure.oid=pg_catalog.to_regprocedure('zeka.reject_writes_during_export_fence()')
                  AND acl.grantee=0
                  AND acl.privilege_type='EXECUTE'
              )
            """));
        await ExecuteAdministratorAsync("DROP TABLE public.issue45_unknown_client");
        await RlsSecurityManifestVerifier.VerifyAsync(verification, typeof(ApplicationDbContext).Assembly);
    }

    private static DeploymentDbContext Deployment(string connectionString) => new(
        new DbContextOptionsBuilder<DeploymentDbContext>().UseNpgsql(connectionString).Options);

    private string Connection(string username, string password) =>
        new NpgsqlConnectionStringBuilder(postgres.GetConnectionString())
        { Username = username, Password = password }.ConnectionString;

    private async Task ExecuteAdministratorAsync(string sql)
    {
        await using var connection = new NpgsqlConnection(postgres.GetConnectionString());
        await connection.OpenAsync();
        await using var command = new NpgsqlCommand(sql, connection);
        await command.ExecuteNonQueryAsync();
    }

    private async Task<T> ExecuteAdministratorScalarAsync<T>(string sql)
    {
        await using var connection = new NpgsqlConnection(postgres.GetConnectionString());
        await connection.OpenAsync();
        await using var command = new NpgsqlCommand(sql, connection);
        return (T)(await command.ExecuteScalarAsync())!;
    }

    private static string ReadBootstrapScript(string fileName)
    {
        var directory = new DirectoryInfo(AppContext.BaseDirectory);
        while (directory is not null)
        {
            var candidate = Path.Combine(directory.FullName, "Deployments", "database", fileName);
            if (File.Exists(candidate)) return File.ReadAllText(candidate);
            directory = directory.Parent;
        }
        throw new FileNotFoundException("The reviewed database role bootstrap script was not found.", fileName);
    }
}
