apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminareadb-deployment
  labels:
    app: adminareadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminareadb
  template:
    metadata:
      name: adminareadb-pod
      labels:
        app: adminareadb
    spec:
      containers:
        - name: zekaadminareadb
          image: postgres
          ports:
            - containerPort: 5432
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "500m"
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: adminarea-secret
                  key: adminarea-root-user                  
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: adminarea-secret
                  key: adminarea-root-pwd
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: adminarea-secret
                  key: adminarea-root-db
          readinessProbe:
            exec:
              command: ["psql", "-w", "-U", "postgres", "-d", "zekaAdminAreadb", "-c", "SELECT 1"]
            initialDelaySeconds: 15
            timeoutSeconds: 2
          livenessProbe:
            exec:
              command: ["psql", "-w", "-U", "postgres", "-d", "zekaAdminAreadb", "-c", "SELECT 1"]
            initialDelaySeconds: 45
            timeoutSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: adminareadb-service
spec:
  selector:
    app: adminareadb
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432