apiVersion: v1
kind: Secret
metadata:
  name: zekadb-secret
type: Opaque
data:
  zekadb-root-user: cG9zdGdyZXM=
  zekadb-root-pwd: YWRtaW4=
  zekadb-root-db: emVrYWRi
stringData:
  zekadb-root-user: postgres
  zekadb-root-pwd: admin
  zekadb-root-db: postgres